/*
 * Copyright 2026 os890
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.os890.jawelte.tests.dbtestdata.scenario66;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.os890.jawelte.module.dbtestdata.api.DbSeed;

/**
 * After {@link DbSeed#forConnection}.cleanInsert() loads rows with
 * explicit ID values into an IDENTITY-typed column, the next INSERT
 * that omits the ID column should receive an auto-generated value
 * past the highest seeded ID. Without that, a typical test pattern -
 * seed fixture from XML, then perform an additional INSERT via JPA -
 * fails on a PK collision because most databases' IDENTITY counters
 * stay at their initial value when explicit IDs are inserted.
 */
class Scenario66Test {

    private Connection connection;

    @BeforeEach
    void openConnection() throws Exception {
        connection = DriverManager.getConnection(
                "jdbc:h2:mem:scenario66;DB_CLOSE_DELAY=-1", "sa", "");
        try (Statement statement = connection.createStatement()) {
            statement.execute(
                    "CREATE TABLE ORDER_ITEM ("
                    + "  ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "  QUANTITY INT)");
        }
    }

    @AfterEach
    void closeConnection() throws Exception {
        if (connection != null) {
            try (Statement statement = connection.createStatement()) {
                statement.execute("DROP ALL OBJECTS");
            }
            connection.close();
        }
    }

    /**
     * Reproduces the LNP scenario-02 PK-collision: seed 5 rows with
     * explicit IDs 1..5, then INSERT a row without specifying ID -
     * the IDENTITY counter should auto-assign 6, not 1 (which would
     * collide with the seeded row).
     */
    @Test
    void identityCounterAdvancesPastHighestSeededId() throws Exception {
        String dataset = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                + "<dataset>"
                + "<ORDER_ITEM ID=\"1\" QUANTITY=\"10\"/>"
                + "<ORDER_ITEM ID=\"2\" QUANTITY=\"20\"/>"
                + "<ORDER_ITEM ID=\"3\" QUANTITY=\"30\"/>"
                + "<ORDER_ITEM ID=\"4\" QUANTITY=\"40\"/>"
                + "<ORDER_ITEM ID=\"5\" QUANTITY=\"50\"/>"
                + "</dataset>";

        DbSeed.forConnection(connection)
                .datasetContent(dataset)
                .cleanInsert()
                .execute();

        // Sanity: 5 rows seeded.
        try (Statement statement = connection.createStatement();
                ResultSet count = statement.executeQuery(
                        "SELECT COUNT(*) FROM ORDER_ITEM")) {
            count.next();
            assertThat(count.getInt(1)).isEqualTo(5);
        }

        // Now INSERT without specifying ID. The IDENTITY column
        // should pick a fresh value past 5.
        try (Statement statement = connection.createStatement()) {
            statement.execute("INSERT INTO ORDER_ITEM (QUANTITY) VALUES (60)");
        }

        try (Statement statement = connection.createStatement();
                ResultSet ids = statement.executeQuery(
                        "SELECT ID FROM ORDER_ITEM ORDER BY ID")) {
            for (long expected = 1L; expected <= 5L; expected++) {
                ids.next();
                assertThat(ids.getLong(1)).isEqualTo(expected);
            }
            ids.next();
            assertThat(ids.getLong(1))
                    .as("IDENTITY counter should advance past the highest seeded ID")
                    .isGreaterThan(5L);
        }
    }
}
